### ISSUE TITLE
[request] separate Focus Mode for tree view into it's own package

### ISSUE THREAD

**Issue by ha404** [jmcalaway/atom-genesis-ui#9]
I would love to use this feature on another UI.

Thanks!

**Comment by ha404** [comment]
I created it myself. For those who want just this feature, edit your Atom's stylesheet with this:

``` css
/**
 * focus mode for tree-view
 */
@import "ui-variables";
.tree-view {
  li {
    transition: opacity 100ms ease-in-out;
    &.project-root > ol > .file > span {
      &:hover {
        opacity: 1;
      }
      opacity: 0.5;
    }
  }
  li:not(.project-root) .entries {
    border-left: 1px solid lighten(@tree-view-background-color, 2%);
  }
  &:not(:hover) {
    li {
      &.collapsed,
      &.project-root > ol > .file > span {
        opacity: 0.15;
      }
      &.selected,
      &.selected > * {
        opacity: 1 !important;
      }
      &.selected:before {
        // background: none;
      }
    }
  }
}
```
